sonar.projectKey=morzan1001_Portwhine
sonar.organization=morzan1001

sonar.projectName=Portwhine

sonar.sources=backend/cmd,backend/internal,backend/pkg,frontend/src
sonar.tests=backend/internal,frontend/src
sonar.test.inclusions=**/*_test.go,**/*.test.ts,**/*.test.tsx

sonar.go.coverage.reportPaths=backend/coverage.out
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/gen/**,**/vendor/**
