# Base image
FROM base:1.0

# Metadata
LABEL maintainer="Morzan <morzan1001@gmail.com>"
LABEL version="1.0"
LABEL description="Dockerfile for the resolver module of Portwhine"

# Copy the Nmap helper module to the working directory
COPY src/modules/resolver /src/resolver

# Set the working directory
WORKDIR /src

# Start the Nmap helper module
CMD ["python", "-m", "resolver.main"]