# Base image
FROM base:1.0

# Metadata
LABEL maintainer="Morzan <morzan1001@gmail.com>"
LABEL version="1.0"
LABEL description="Dockerfile for the ffuf module of Portwhine"

# Copy the ffuf module to the working directory
COPY src/modules/ffuf /src/ffuf
COPY src/utils /src/utils

# Install ffuf
RUN apk add --no-cache ffuf

# Set the working directory
WORKDIR /src

# Start the Certstream client module
CMD ["python", "-m", "ffuf.main"]