# Base image
FROM base:1.0

# Metadata
LABEL maintainer="Morzan <morzan1001@gmail.com>"
LABEL version="1.0"
LABEL description="Dockerfile for the screenshot module of Portwhine"

# Copy the screenshot module to the working directory
COPY src/modules/screenshot /src/screenshot
COPY src/utils /src/utils

# Install Chromium
RUN apk add --no-cache chromium chromium-chromedriver

# Set the working directory
WORKDIR /src

# Install dependencies with Poetry
RUN POETRY_VIRTUALENVS_CREATE=false poetry install --no-interaction --no-ansi --with screenshot --without dev

# Start the Certstream client module
CMD ["python", "-m", "screenshot.main"]