# Base image
FROM base:1.0

# Metadata
LABEL maintainer="Morzan <morzan1001@gmail.com>"
LABEL version="1.0"
LABEL description="Dockerfile for the webappanalyzer module of Portwhine"

# Copy the webappanalyzer module to the working directory
COPY src/modules/webappanalyzer /src/webappanalyzer

# Set the working directory
WORKDIR /src

# Start the Certstream client module
CMD ["python", "-m", "webappanalyzer.main"]