metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "memory"
    - "network"  
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

output.elasticsearch:
  hosts: ["https://${ES_HOST}:9200"]
  username: "${METRICBEAT_WRITER_USER}"
  password: "${METRICBEAT_WRITER_PASSWORD}"
  ssl:
    enabled: true
    certificate_authorities: ["/usr/share/metricbeat/certs/ca.crt"]
    certificate: "/usr/share/metricbeat/certs/metricbeat.crt"
    key: "/usr/share/metricbeat/certs/metricbeat.key"
    verification_mode: full 

# Runtime (Writer-User) darf keine Setup/ILM/Template/Dashboard Writes versuchen.
setup.ilm.enabled: false
setup.template.enabled: false
setup.dashboards.enabled: false
